template = "blog-post.html"

title = "AA Defence"
subtitle = "Made a simple minigame"
post_date = "2025-03-11"

description = """
A 2D survival game where you operate an anti-air gun against endless enemy waves. Each run is short and luck based. The game is complete with minor issues. Some mechanics, especially enemy spawning, are inconsistent. Occasionally, the game gets way too easy or absurdly difficult. I am still very happy with how it came out, after all it was just a weekend project.
"""

future_plans = "Despite the game needing polish im all done with it, one weekend was more then it deserved."

resources = [
    { text = "details on this project", url = "/projects/aa-defence" }
]
