template = "blog-post.html"

title = "Hangman"
subtitle = "Final Version"
post_date = "3/29/2025"

description = """
The final version of my Hangman game. I added a couple of characters before the game starts, revealed the word after the game ends, and used a JSON file to filter about 1150 words. There's a 30-second timer now, and I made the input bar more visible. No plans for further updates.
"""

future_plans = """
None.
"""

resources = [
    { text = "details on this project", url = "/projects/hangman" }
]

