template = "blog-post.html"

title = "My Website 01"
subtitle = "first deployment"
post_date = "3/4/2025"

description = """
It took me 3 days to make this site, which is a lot since it's actually vary simple, the project only 5 main pages so far. I used golang to make this site, mostly because i really like its syntax, however named templates, which it provides is also really useful. To publish this site I used render because it is free, my domain is from NameCheap, it cost me 9$.
"""

pictures = [
]

technologies_used = ""

future_plans = """
There is still a lot that needs to be done and this is definitely not my last blog on this subject. In the future i want to refactor the code since it is so repetative, should be easy with golang. I also want to change the server provider since render is so slow. Responsiveness is also a major problem, this site has none. Regarding tech im also considering using svelte and hugo in the future if i feel like.
"""

resources = [
    { text = "details no this project", url = "projects/my-website" },
]
