template = "project-post.html"

title = "Hangman – Final Version"
subtitle = "Details On This Project"
post_date = "3/25/2025"

description = """
Originally made for my university class, Hangman is a very simple 2D puzzle game. The rules are simple: guess the word or the rat gets it.
"""

iframe_src = "/static/games/hangman/index.html"
iframe_width = "640"
iframe_height = "360"
iframe_allowfullscreen = true

pictures = [
]

technologies_used = "I used Godot to make the game because it uses Python syntax (project was for a Python class), and also because I prefer it way more over Raylib-py, which I originally planned to use. For sprites, I used Aseprite."

future_plans = """
None. This is the final version of the game, and I don't plan on making any further updates.
"""

resources = [
    { text = "itch.io", url = "https://knyaz26.itch.io/hangman" },
    { text = "code from github", url = "https://github.com/knyaz26/hangman" }
]

logs = [
    { text = "final version", url = "/blog/hangman-02" },
    { text = "first version", url = "/blog/hangman-01" }
]

